### ISSUE TITLE
Unable to compile models

### ISSUE THREAD

**Issue by francesshei** [nest/nestml#781]
I have successfully installed NESTML v.5.0.0 from `pip` in a `pyenv` environment with NEST 3.1 installed. 
However, when running the same code as the Izhikevich tutorial from the docs, compilation fails when `make` comand is invoked in the `/tmp/nestml-component` folder.

Specs: 
- Ubuntu OS  20.04.4 LTS
- Python version: 3.10.4
- NEST version:  3.1
- NESTML version: 5.0.0
- CMake version: 3.16.3

Full output when running the Python script:
```
              -- N E S T --
  Copyright (C) 2004 The NEST Initiative

 Version: nest-3.1
 Built: May 13 2022 16:43:00

 This program is provided AS IS and comes with
 NO WARRANTY. See the file LICENSE for details.

 Problems or suggestions?
   Visit https://www.nest-simulator.org

 Type 'nest.help()' to find out more about NEST.

Warning: PyGSL is not available. The stiffness test will be skipped.
Warning: No module named 'pygsl'


-- The CXX compiler identification is GNU 9.4.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done

-------------------------------------------------------
nestmlmodule Configuration Summary
-------------------------------------------------------

C++ compiler         : /usr/bin/c++
Build static libs    : OFF
C++ compiler flags   : 
NEST compiler flags  :  -std=c++11 -O2 -Wall -fopenmp -fdiagnostics-color=auto
NEST include dirs    :  -I/home/modelling/.pyenv/versions/3.10.4/envs/nestml/include/nest -I/usr/include -I/usr/include -I/usr/include -I/usr/include
NEST libraries flags : -L/home/modelling/.pyenv/versions/3.10.4/envs/nestml/lib/nest -lnestutil -lnest -lsli -lnestkernel -fopenmp /usr/lib/x86_64-linux-gnu/libltdl.so /usr/lib/x86_64-linux-gnu/libreadline.so /usr/lib/x86_64-linux-gnu/libncurses.so /usr/lib/x86_64-linux-gnu/libgsl.so /usr/lib/x86_64-linux-gnu/libgslcblas.so

-------------------------------------------------------

You can now build and install 'nestmlmodule' using
  make
  make install

The library file libnestmlmodule.so will be installed to
  /home/modelling/.pyenv/versions/3.10.4/envs/nestml/lib/nest
The module can be loaded into NEST using
  (nestmlmodule) Install       (in SLI)
  nest.Install(nestmlmodule)   (in PyNEST)

CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.16)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/nestml-component
Scanning dependencies of target nestmlmodule_lib
[ 16%] Building CXX object CMakeFiles/nestmlmodule_lib.dir/nestmlmodule.o
In file included from /home/modelling/.pyenv/versions/3.10.4/envs/nestml/include/nest/model_manager.h:31,
                 from /home/modelling/.pyenv/versions/3.10.4/envs/nestml/include/nest/kernel_manager.h:31,
                 from /home/modelling/.pyenv/versions/3.10.4/envs/nestml/include/nest/connection_manager_impl.h:35,
                 from /tmp/nestml-component/nestmlmodule.cpp:26:
/home/modelling/.pyenv/versions/3.10.4/envs/nestml/include/nest/genericmodel.h: In instantiation of ‘class nest::GenericModel<izhikevich_tutorial>’:
/home/modelling/.pyenv/versions/3.10.4/envs/nestml/include/nest/model_manager_impl.h:55:18:   required from ‘nest::index nest::ModelManager::register_node_model(const Name&, bool, std::string) [with ModelT = izhikevich_tutorial; nest::index = long unsigned int; std::string = std::__cxx11::basic_string<char>]’
/tmp/nestml-component/nestmlmodule.cpp:103:96:   required from here
/home/modelling/.pyenv/versions/3.10.4/envs/nestml/include/nest/genericmodel.h:116:12: error: cannot declare field ‘nest::GenericModel<izhikevich_tutorial>::proto_’ to be of abstract type ‘izhikevich_tutorial’
  116 |   ElementT proto_;
      |            ^~~~~~
In file included from /tmp/nestml-component/nestmlmodule.cpp:47:
/tmp/nestml-component/izhikevich_tutorial.h:105:7: note:   because the following virtual functions are pure within ‘izhikevich_tutorial’:
  105 | class izhikevich_tutorial : public nest::ArchivingNode
      |       ^~~~~~~~~~~~~~~~~~~
In file included from /home/modelling/.pyenv/versions/3.10.4/envs/nestml/include/nest/common_synapse_properties.h:30,
                 from /home/modelling/.pyenv/versions/3.10.4/envs/nestml/include/nest/connector_base.h:39,
                 from /home/modelling/.pyenv/versions/3.10.4/envs/nestml/include/nest/connection_manager.h:36,
                 from /home/modelling/.pyenv/versions/3.10.4/envs/nestml/include/nest/connection_manager_impl.h:26,
                 from /tmp/nestml-component/nestmlmodule.cpp:26:
/home/modelling/.pyenv/versions/3.10.4/envs/nestml/include/nest/node.h:257:16: note: 	‘virtual void nest::Node::calibrate()’
  257 |   virtual void calibrate() = 0;
      |                ^~~~~~~~~
make[2]: *** [CMakeFiles/nestmlmodule_lib.dir/build.make:63: CMakeFiles/nestmlmodule_lib.dir/nestmlmodule.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:79: CMakeFiles/nestmlmodule_lib.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
Traceback (most recent call last):
  File "/home/modelling/.pyenv/versions/nestml/lib/python3.10/site-packages/pynestml/codegeneration/nest_builder.py", line 151, in build
    subprocess.check_call(make_all_cmd, stderr=subprocess.STDOUT, shell=shell,
  File "/home/modelling/.pyenv/versions/3.10.4/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', 'all']' returned non-zero exit status 2.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/modelling/Documents/nestml/test-Izi.py", line 10, in <module>
    generate_nest_target(input_path="izhikevich_solution.nestml",
  File "/home/modelling/.pyenv/versions/nestml/lib/python3.10/site-packages/pynestml/frontend/pynestml_frontend.py", line 189, in generate_nest_target
    generate_target(input_path, target_platform="NEST", target_path=target_path, logging_level=logging_level,
  File "/home/modelling/.pyenv/versions/nestml/lib/python3.10/site-packages/pynestml/frontend/pynestml_frontend.py", line 158, in generate_target
    if not process() == 0:
  File "/home/modelling/.pyenv/versions/nestml/lib/python3.10/site-packages/pynestml/frontend/pynestml_frontend.py", line 294, in process
    _builder.build()
  File "/home/modelling/.pyenv/versions/nestml/lib/python3.10/site-packages/pynestml/codegeneration/nest_builder.py", line 154, in build
    raise GeneratedCodeBuildException('Error occurred during \'make all\'! More detailed error messages can be found in stdout.')
pynestml.exceptions.generated_code_build_exception.GeneratedCodeBuildException: Error occurred during 'make all'! More detailed error messages can be found in stdout.
```

**Comment by pnbabu** [comment]
@francesshei Recently, the `calibrate()` function in NEST has been renamed to `pre_run_hook()` (see [here](https://github.com/nest/nest-simulator/pull/2336)). The latest NESTML release 5.0.0 is in-line with the latest NEST master which has the mentioned change. So could I ask you to use the latest NEST master instead of version `3.1`? If in case you do not want to use the latest NEST master, you could install the previous release candidate of NESTML by `pip uninstall nestml; pip install nestml==5.0.0.rc2`. Hope this helps!

**Comment by francesshei** [comment]
Downgrading to `nestml==5.0.0.rc2` solved the issue! Thanks
